services:
  app:
    image: jorgenklausen/mediamtx_bachelor:latest
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__DefaultConnection=Data Source=/data/app.db
      - Oidc__Authority=https://thurs.uia.no:4444
      - Oidc__ClientId=${OIDC_CLIENT_ID}
      - Oidc__ClientSecret=${OIDC_CLIENT_SECRET}
    volumes:
      - app-data:/data
    networks:
      - internal

  mediamtx:
    build:
      context: .
      dockerfile: dockerfile.mediamtx
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=false
    ports:
      - "8888:8888"
      - "8554:8554"
      - "1936:1936"
    volumes:
      - ./mediamtx/mediamtx.yml:/mediamtx.yml
    networks:
      - internal
  
  watchtower:
    image: containrrr/watchtower:1.4.0
    restart: unless-stopped
    environment:
      - DOCKER_API_VERSION=1.44
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 --label-enable

volumes:
  app-data:

networks:
  internal: